spring.application.name=Sample-5
spring.datasource.url=jdbc:mysql://localhost:3306/juice_shop
spring.datasource.username=root
spring.datasource.password=Jash@4233

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080